// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	models "github.com/shaikrasheed99/authentication-service/models"
	requests "github.com/shaikrasheed99/authentication-service/requests"
	mock "github.com/stretchr/testify/mock"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// SaveUser provides a mock function with given fields: _a0
func (_m *IAuthService) SaveUser(_a0 *requests.SignupRequest) (*models.User, error) {
	ret := _m.Called(_a0)

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*requests.SignupRequest) (*models.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*requests.SignupRequest) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*requests.SignupRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
