// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IBrokerHandler is an autogenerated mock type for the IBrokerHandler type
type IBrokerHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *IBrokerHandler) Handle(_a0 *gin.Context) {
	_m.Called(_a0)
}

// Health provides a mock function with given fields: _a0
func (_m *IBrokerHandler) Health(_a0 *gin.Context) {
	_m.Called(_a0)
}

// NewIBrokerHandler creates a new instance of IBrokerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBrokerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBrokerHandler {
	mock := &IBrokerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
